import crypto from 'node:crypto';
const env=(n,f='')=>process.env[n]||f; const ENDPOINT=env('APPWRITE_ENDPOINT'),PROJECT=env('APPWRITE_PROJECT_ID'),KEY=env('APPWRITE_API_KEY'),DB=env('APPWRITE_DATABASE_ID','music'),ORDERS=env('APPWRITE_ORDERS_TABLE','orders'),FILES=env('APPWRITE_FILES_TABLE','order_files'),EVENTS=env('APPWRITE_EVENTS_TABLE','order_events'),MESSAGES=env('APPWRITE_MESSAGES_TABLE','messages'),BUCKET=env('APPWRITE_STORAGE_BUCKET','order-files'),ADMIN=env('ADMIN_TOKEN'),SITE=env('SITE_URL','https://songs.racharlagpt.in');
const cors={'Access-Control-Allow-Origin':SITE,'Access-Control-Allow-Headers':'Content-Type,Authorization,X-File-Name','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS'};const json=(res,d,s=200)=>res.json(d,s,cors),bad=(res,m,s=400)=>json(res,{error:m},s);
async function aw(path,opt={}){const r=await fetch(ENDPOINT.replace(/\/$/,'')+'/v1'+path,{...opt,headers:{'X-Appwrite-Project':PROJECT,'X-Appwrite-Key':KEY,...(opt.headers||{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}}if(!r.ok)throw Error(d.message||t);return d}
const q=(a,v)=>encodeURIComponent(`equal(\"${a}\",${JSON.stringify([String(v)])})`);
async function rows(t,query=''){ const u = '/tablesdb/'+DB+'/tables/'+t+'/rows'+(query ? ('?queries[]='+query+'&limit=100') : '?limit=100'); return (await aw(u)).rows || []; }
async function create(t,data){return aw(`/tablesdb/${DB}/tables/${t}/rows`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rowId:'unique()',data})})}async function update(t,id,data){return aw(`/tablesdb/${DB}/tables/${t}/rows/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({data})})}
function auth(req){return ADMIN&&req.headers.authorization===`Bearer ${ADMIN}`}
function safe(o){return{...o,access_token_hash:undefined}}
export default async({req,res,error})=>{try{if(req.method==='OPTIONS')return json(res,{});if(req.path==='/login'&&req.method==='POST'){if(!ADMIN)return bad(res,'Admin token is not configured',500);const p=String((req.bodyJson||{}).password||'');if(!p||p.length!==ADMIN.length||!crypto.timingSafeEqual(Buffer.from(p),Buffer.from(ADMIN)))return bad(res,'Invalid credentials',401);return json(res,{ok:true,token:ADMIN})}if(!auth(req))return bad(res,'Unauthorized',401);
 if(req.method==='GET'&&req.path==='/orders'){const r=await rows(ORDERS);r.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));return json(res,{orders:r.map(safe)});}
 let m=req.path.match(/^\/orders\/([^/]+)$/);if(req.method==='GET'&&m){const no=decodeURIComponent(m[1]),o=(await rows(ORDERS,q('order_number',no)))[0];if(!o)return bad(res,'Order not found',404);const files=await rows(FILES,q('order_number',no)),messages=await rows(MESSAGES,q('order_number',no));return json(res,{order:safe(o),files,messages});}
 if(req.method==='PATCH'&&m){const no=decodeURIComponent(m[1]),o=(await rows(ORDERS,q('order_number',no)))[0];if(!o)return bad(res,'Order not found',404);const b=req.bodyJson||{},allowed=['ORDER_RECEIVED','PAYMENT_VERIFIED','REQUIREMENTS_RECEIVED','IN_PRODUCTION','QUALITY_CHECK','READY','DELIVERED','NEEDS_MORE_INFORMATION','REVISION_REQUESTED'];if(b.status&&!allowed.includes(b.status))return bad(res,'Invalid status');const data={};if(b.status)data.status=b.status;if(typeof b.revision_count==='number')data.revision_count=b.revision_count;if(b.admin_note)data.admin_note=String(b.admin_note).slice(0,2000);await update(ORDERS,o.$id,data);await create(EVENTS,{order_number:no,event:b.status||'ORDER_UPDATED',created_at:new Date().toISOString()});return json(res,{ok:true});}
 m=req.path.match(/^\/orders\/([^/]+)\/messages$/);if(req.method==='POST'&&m){const no=decodeURIComponent(m[1]),body=String((req.bodyJson||{}).body||'').trim();if(!body||body.length>2000)return bad(res,'Message is empty or too long');await create(MESSAGES,{order_number:no,sender_role:'admin',body,created_at:new Date().toISOString()});return json(res,{ok:true});}
 m=req.path.match(/^\/orders\/([^/]+)\/mp3$/);if(req.method==='POST'&&m){const no=decodeURIComponent(m[1]),o=(await rows(ORDERS,q('order_number',no)))[0];if(!o)return bad(res,'Order not found',404);const bytes=req.bodyBinary;if(!bytes?.length||bytes.length>30*1024*1024)return bad(res,'MP3 is empty or too large');const name=(req.headers['x-file-name']||`${no}-final.mp3`).replace(/[^a-zA-Z0-9._-]/g,'_');const f=new FormData();f.append('fileId','unique()');f.append('file',new Blob([bytes],{type:'audio/mpeg'}),name);const up=await aw(`/storage/buckets/${BUCKET}/files`,{method:'POST',body:f});await create(FILES,{order_number:no,type:'mp3',file_id:up.$id,file_name:name,created_at:new Date().toISOString()});await update(ORDERS,o.$id,{status:'READY'});await create(EVENTS,{order_number:no,event:'SONG_READY',created_at:new Date().toISOString()});return json(res,{ok:true,file_id:up.$id,status:'READY'});}
 return bad(res,'Route not found',404);
}catch(e){error(e?.stack||String(e));return bad(res,'Server error',500)}};
